name: CI/CD Flutter / Analyze Code
on: [pull_request]

jobs:
  analyze:
    name: Run Analyze Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.7"
          channel: "stable"

      - name: Update dependencies
        run: |
          flutter pub get
      - name: Analyze Code
        run: flutter analyze
